interfaces:
  - { name: "ge-0/0/0", description: "uplink" }
  - { name: "ge-0/0/1", description: "downlink" }
lacp_mode: "active"

ansible_connect_timeout: 60
ansible_command_timeout: 300     
ansible_ssh_retries: 3