vjunos_vlan_ip: "172.16.10.3/24"
ospf_router_id: 2.2.2.2
ospf_reference_bw: 10000
ospf_passive_area: "0.0.0.0"
ospf_passive_ifaces:
  - lo0.0
  - ge-0/0/3.0
  - fxp0.0

ospf_areas:
  "0.0.0.0":
    interfaces:
      - { name: ge-0/0/2.5, metric: 5 }  # łącze do R1
  "0.0.0.1":
    interfaces:
      - { name: ge-0/0/1.10 }
      - { name: ge-0/0/1.20 }
      - { name: ge-0/0/1.30 }
