vjunos_vlan_ip: "172.16.10.2/24"
ospf_router_id: 1.1.1.1
ospf_reference_bw: 10000
ospf_passive_area: "0.0.0.0"    
ospf_passive_ifaces:
  - lo0.0
  - ge-0/0/3.0
  - fxp0.0

ospf_areas:
  "0.0.0.0":
    interfaces:
      - { name: ge-0/0/2.5, metric: 5 }  
  "0.0.0.1":
    interfaces:
      - { name: ge-0/0/0.10 }            
      - { name: ge-0/0/0.20 }
      - { name: ge-0/0/0.30 }

grpc_cert_id: "grpc-server"
grpc_enable: true
grpc_port: 55000
grpc_cert_type: "rsa"      
grpc_cert_size: 2048
grpc_cert_domain: "router.local"
grpc_cert_subject: "CN=router.local,OU=Net,O=Lab,L=Poznan,ST=Wielkopolskie,C=PL"
grpc_generate_certificate: true